# fly.toml file generated for hanami-phlex-test-idea on 2023-03-02T10:10:54-06:00

app = "hanami-phlex-test-idea"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

# [deploy]
  # release_command = "bin/hanami db migrate"

[env]
  PORT = "2300"
  HANAMI_PORT="2300"
  HANAMI_ENV="production"
  HANAMI_MAX_THREADS=16
  HANAMI_MIN_THREADS=2
  HANAMI_WEB_CONCURRENCY=8

[processes]
  web = "bundle exec puma -C config/puma.rb"
  # web = "bundle exec hanami server -p $PORT"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2300
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
